### ISSUE TITLE
Reading Time issue

### ISSUE THREAD

**Issue by zakirsajib** [g00glen00b/gatsby-blog#1]
I am getting this error:

 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'fields' on type 'wordpress__POST'.

File: src/templates/post.js

`query BlogPostByID($id: String!) {
    wordpressPost(id: { eq: $id }) {
      id
      title
      slug
      content
      date(formatString: "MMMM DD, YYYY")
      categories {
        name
        slug
      }
      tags {
        name
        slug
      }
      author {
        name
        slug
      }
      featured_media{
        localFile{
          childImageSharp{
            fluid(maxWidth: 1152, quality: 100) {
                ...GatsbyImageSharpFluid
            }
          }
        }
      }
      fields{
        readingTime {
          text
        }
      }
    }
  }`

**Comment by g00glen00b** [comment]
I assume you're using `gatsby-wordpress-reading-time`? Can you show your `gatsby-config.js`?

**Comment by zakirsajib** [comment]
Its fixed.
