### ISSUE TITLE
Inline images returned from wp are in base64

### ISSUE THREAD

**Issue by matthewtmoran** [g00glen00b/gatsby-blog#58]
Hi Dimitri,

I was following your blog post, https://dimitr.im/optimize-loading-images-wordpress-gatsby.  Conceptually, it's exactly what I want to do.  Thank you for it!  

I'm having some trouble with the result from my graphql query, however.  The `src` for my inline images from wordpress posts are not returning the wordpress site's url, instead it is returning inline base64 like, `data:image/jpeg;base64,/9j/2wBDABALDA4MCh...`.  Therefore, I'm unable to map the images to the `allWordpressWpMedia` data.   The `source_url` from `allWordpressWpMedia` returns what I would expect.

Any thoughts?  Am I missing something?

**Comment by g00glen00b** [comment]
That's strange indeed. Do you use some WordPress plugin to optimize images somehow that may cause the `src` of the images to become a base64 URL? In that case, you may have to disable those plugins so you can use Gatsby to optimize them.

**Comment by matthewtmoran** [comment]
The only plugin I have installed are:
- ACF to REST API
- Advanced Custom Fields
- Akismet Anti-Spam
- WP fail2ban
- WP REST API Menus
- Hello Dolly
- Code Snippets

I disabled them all but still no luck.  

If I visit a post through the wordpress domain, the images are using the path that I would expect.  It's only through the graphql query that they seem to be base64.

**Comment by matthewtmoran** [comment]
If I view the wordpress rest api endpoint for posts in the browser, the images are using the path that I would expect as well.

**Comment by g00glen00b** [comment]
Can you also verify if the WordPress API is returning the images properly as well? To check it, you have to call the `/wp-json/wp/v2/posts` API, for example `http://my-wordpress-site.com/wp-json/wp/v2/posts`.

The Gatsby plugin imports the data from the API, so if it's correct there as well, it's certainly something that's happening within Gatsby.

If this also points to the original `src`, can you tell me if you have additional Gatsby plugins installed and share the GraphQL query you used to verify what the `src` attribute contains?

**Comment by matthewtmoran** [comment]
Yes, the WordPress API is returning the images properly as well.

These are the Gatsby plugins I'm using:
```
plugins: [
    `gatsby-plugin-sitemap`,
    `gatsby-plugin-emotion`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-typescript`,
    `gatsby-plugin-react-helmet`,
    `@bumped-inc/gatsby-plugin-optional-chaining`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        baseUrl: `admin.interiorrising.com`,
        protocol: `http`,
        hostingWPCOM: false,
        useACF: true,
        verbose: true,
        includedRoutes: [
          "**/categories",
          "**/posts",
          "**/pages",
          "**/media",
          "**/tags",
          "**/taxonomies",
          "**/users",
        ],
        excludedRoutes: [],
        normalizer: function({ entities }) {
          return entities
        },
        plugins: [
          {
            resolve: `gatsby-wordpress-inline-images`,
            options: {
              baseUrl: `admin.interiorrising.com`,
              protocol: `http`,
            },
          },
        ],
      },
    },
    {
      resolve: "gatsby-source-instagram",
      options: {
        username: "jilliankmoran__",
      },
    },
    {
      resolve: "gatsby-plugin-webpack-bundle-analyzer",
      options: {
        production: true,
        disable: !process.env.ANALYZE_BUNDLE_SIZE,
        generateStatsFile: true,
        analyzerMode: "static",
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
```

In the GraphQL playground I'm using this query:

```
query MyQuery {
  allWordpressPost {
    edges {
      node {
        content
      }
    }
  }
}

```

In the component my query looks like this:
```

const pageQuery = graphql`
  query {
    data: allWordpressPost(
      filter: { categories: { elemMatch: { name: { eq: "Photos" } } } }
    ) {
      posts: edges {
        post: node {
          id
          slug
          status
          template
          format
          date
          title
          excerpt
          content
        }
      }
    }
  }
`
```

I really appreciate your time with this!

**Comment by g00glen00b** [comment]
I think the `gatsby-wordpress-inline-images` plugin might be doing this. This plugin basically does the same thing as I do within my tutorial, but it does this way earlier (while importing).

The reason why they conflict is because the Gatsby image processing does indeed replace the `src` with a base64 string. Since `gatsby-wordpress-inline-images` does this already while importing, the original `src` is gone afterwards.

My suggestion is to either use the `gatsby-wordpress-inline-images-plugin` (no clue if it works 100%) or to use the method I used within my tutorial.

**Comment by matthewtmoran** [comment]
Confirmed!  There was conflict with your method and `gatsby-wordpress-inline-images`.  By removing `gatsby-wordpress-inline-images` plugin the `src` attribute returned as expected.  Thank you!
