### ISSUE TITLE
Image not displayed correctly

### ISSUE THREAD

**Issue by fonio** [g00glen00b/gatsby-blog#71]
Hi
In https://dimitr.im/monitoring-spring-prometheus-grafana

In the chanpter "Checking, double checking", the image "Prometheus targets" is not rendered,

I am using Win10. Experienced on Chrome (Version 83.0.4103.61 (Official Build) (64-bit))
and double checked (ha ha) on MS Edge (Version 83.0.478.37 (Official build) (64-bit))

HTH, Itai

**Comment by g00glen00b** [comment]
Thanks! Looks like I didn't properly clean up this article when I exported it from WordPress. It's fixed now, and it will be live in about 10 minutes.
