### ISSUE TITLE
HTTP headers can be set when sending queries via GraphiQL

### ISSUE THREAD

**Issue by mxmlnglt** [g00glen00b/gatsby-blog#75]
**Blogpost**:

Hello Dimitri, I have a remark about your article [Securing your GraphQL API with Spring Security](https://dimitr.im/graphql-spring-security) from March 2020.

**Description**:

Near the end, you're saying "it doesn’t seem that GraphiQL doesn’t support setting HTTP headers".
Well, I think the correct wording (double negatives are tricky ^^) would probably be *it doesn’t seem that GraphiQL supports setting HTTP headers* (given the following sentence)... which by the way is wrong, as can be seen below:

https://github.com/graphql-java-kickstart/graphql-spring-boot#enable-graphiql
*Headers that are used when sending the GraphiQL queries can be set by defining them in the graphiql.headers group.*

Just to let you know.

**Comment by g00glen00b** [comment]
I fixed the double negation. You're right about being able to configure headers within application properties, but what I meant is that you can't configure the headers through the interface itself (as far as I know). I tried to clarify that as well now.
