### ISSUE TITLE
Comment on twitter cards and open graph

### ISSUE THREAD

**Issue by jackkrone** [g00glen00b/gatsby-blog#94]
**Page**:

https://dimitr.im/generating-social-cards-gatsby

**Description**:

You say:

"Another thing you have to be aware of is that Twitter uses the property attribute to define the property name, while Open Graph utilizes the name attribute."

This is backwards. Twitter uses name, OG uses property.

**Comment by g00glen00b** [comment]
Thanks for letting me know! I'll fix it immediately.
